### ISSUE TITLE
Current workflow for syntax errors

### ISSUE THREAD

**Issue by ryanjdillon** [sirtaj/vim-openscad#7]
This looks like a great project, and I'd be really interested in flagging syntax errors as you mentioned in the README. I haven't written vimscript to date, but I'd be happy to give a go at something.

For now I will see if I can use a linter instead. I came across [this one](https://github.com/Maxattax97/openscad-format), but just wondered if you have any suggestions on this front?

**Comment by sirtaj** [comment]
I'd be grateful for any assistance you can provide on error flagging.

An external linting tool is a somewhat orthogonal effort, I think. Perhaps adding quickfix support for the linter and the compiler would be helpful, and probably a more approachable introduction to vimscript, if you're looking for something to get started.
